[package]
name = "uascv25"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
simple_logger = "5.0.0"
log = "0.4.22"
tokio = {version = "1.40.0", features = ["full"]}
opencv = {version = "0.92.3", features = ["default"]}
